services:
  lol-bot:
    build: .
    container_name: lol-bot
    restart: unless-stopped
    ports:
      - 5433:5433
    env_file:
      - .env
    volumes:
      - bot-data:/app/data

volumes:
  bot-data:
